services:
  - type: web
    plan: free
    name: String Gen Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m StringGen
    repo: https://github.com/Lo-pro-file/StringGen-WD.git      
    branch: main
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUPPORT_CHAT
        sync: false
    autoDeploy: false
